language: rust
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
dd:
  secure: qImiGGkx+K79k5Jjy+TTh6cHSzya639gQhM7OYlpOzGQrjZs2d3bUGQ19brnOy0viJu6JGhaP/TzRQArY9t2xKC7e1pBWe8GU2oUwMYwEbwWKaopri6jI4e0V0Y9CZ64P6stPuwuAM3aYWM7BL+6n/k0/SBwT9KPky/dFTNEGgWYjh+B6Sax0pnIUwL1jKpAaVjtwrMVVxoat3hiMBirtovqg9+d+ixySkRdI4PYv3iZyUwq2s5BCRgbFEi5AUATV4vxSlBEbSB7NcwMBz9Ytykk7RfkBPZLtolQuwsoVnOoS78jQSmZa6mM9v+WnyRUA1Nvw3RfZ70U+dN8k5goU5XTjaXiV/kECP9KdDSnkZhhXA0C31G6DBktvS4hFJU2zyVnD/tT5Gzb3DgvkdjIUxGrQtbW13fjWbrWxAhOD4UxD3snvM/jaW89+1oRpxu2HHQ7ZJZ/ZXZSdvlBRx6o5mY30NAGZtX0Ho4djsFiOHjDd8M8uLxNkZgcHJ1l+zonhWUFLYn1h4DLz/9/B921hraUUSqTCzxacwIU5KPUlFkWErU8V/Cich55e9zVBiKaA58tnlGlAfiJ8T04cgQgt36qXOm2GFKIldPAwxk5zrXn3YtS8UBnvxwilhfDOPElmKlCYOqWizLBMtFuV54pytEkgVtdSG0ttUvIL75MgjE=
