[package]
name = "socrates"
version = "0.1.0"
authors = ["Evgeni Pandurski <epandurski@gmail.com>"]

[dependencies]
regex = "0.1"
rand = "0.3"

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
